# Generated by Django 2.2.7 on 2019-11-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=18, help_text='Longitude coordinate for squirrel sighting point', max_digits=20)),
                ('y', models.DecimalField(decimal_places=18, help_text='Latitude coordinate for squirrel sighting point', max_digits=20)),
                ('unique_squirrel_id', models.CharField(help_text='Identification tag for each squirrel sightings', max_length=20)),
                ('hectare', models.CharField(max_length=3)),
                ('shift', models.CharField(max_length=2)),
                ('date', models.DateField(help_text='Sighting session day and month')),
                ('hectare_squirrel_number', models.IntegerField()),
                ('age', models.CharField(max_length=8)),
                ('primary_fur_color', models.CharField(max_length=8)),
                ('highlight_fur_color', models.CharField(max_length=8)),
                ('combination_of_primary_and', models.CharField(max_length=100)),
                ('color_notes', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('above_ground_sighter', models.CharField(max_length=100)),
                ('specific_location', models.CharField(max_length=100)),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
                ('other_activities', models.CharField(max_length=200)),
                ('kuks', models.BooleanField()),
                ('quaas', models.BooleanField()),
                ('moans', models.BooleanField()),
                ('tail_flags', models.BooleanField()),
                ('tail_twitches', models.BooleanField()),
                ('approaches', models.BooleanField()),
                ('indifferent', models.BooleanField()),
                ('runs_from', models.BooleanField()),
                ('other_interactions', models.CharField(max_length=200)),
                ('geocoded_column', models.CharField(max_length=500)),
            ],
        ),
    ]
