# Generated by Django 2.2.7 on 2019-11-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='above_ground_sighter',
            new_name='above_ground_sighter_measurement',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='combination_of_primary_and',
            new_name='combination_of_primary_and_highlight_color',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='geocoded_column',
            new_name='lat_long',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='borough_boundaries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='city_council_districts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='community_districts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='police_precincts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='zip_codes',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
